### ISSUE TITLE
Add markdown linter runner to the project

### ISSUE THREAD

**Issue by egel** [egel/dotfiles#140]
## Expected Behavior
All markdown code should be lined by my personal .markdownlint.json

## Actual Behavior
There is no markdown linting in the project

**Comment by egel** [comment]
example config for travis

```
    - stage: test
      name: "Lint markdown"
      language: node_js
      node_js:
        - "11"
      before_install:
        - yarn --cmd $DOTFILES_PATH install
      script:
        - yarn --cmd $DOTFILES_PATH run lint-md
```
